import Navbar from '@/components/navbar';
import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NextJS Frontend',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='hu'>
      <body className='min-h-screen bg-gray-50 text-gray-900'>
        <Navbar />
        <main className='mx-auto max-w-6xl px-4 py-8'>{children}</main>
      </body>
    </html>
  );
}
